import type { Skill } from '../types';

type SkillMapping = Pick<
  Skill,
  'commandGroups' | 'commands' | 'sdkModules' | 'toolNames' | 'tags' | 'version'
>;

const MANAGER_COMMAND_GROUPS = [
  'auth',
  'project',
  'sheet',
  'column',
  'view',
  'row',
  'doc',
  'upload',
  'role',
  'permission',
  'row-policy',
  'row-acl',
  'report',
  'ai',
  'canvas',
];

const MANAGER_COMMANDS = [
  'auth login',
  'auth api-key-login',
  'auth refresh',
  'auth status',
  'auth use-team',
  'auth use-project',
  'auth profile',
  'project list',
  'project info',
  'project create',
  'project update',
  'project trash',
  'project restore',
  'project use',
  'sheet list',
  'sheet tree',
  'sheet create',
  'sheet info',
  'sheet update',
  'sheet delete',
  'sheet structure',
  'column list',
  'column create',
  'column update',
  'column delete',
  'view list',
  'view create',
  'row page',
  'row info',
  'row create',
  'row update',
  'row delete',
  'row set-cell',
  'doc create',
  'doc info',
  'doc update',
  'doc delete',
  'doc versions',
  'doc version',
  'doc restore',
  'doc attach-file',
  'doc append-image',
  'upload file',
  'upload mode',
  'role list',
  'role info',
  'role create',
  'role update',
  'role delete',
  'role assign-user',
  'role revoke-user',
  'permission list',
  'permission create',
  'permission update',
  'permission delete',
  'permission set-resource',
  'row-policy list',
  'row-policy create',
  'row-policy update',
  'row-policy delete',
  'row-policy enable',
  'row-policy disable',
  'row-acl list',
  'row-acl grant-user',
  'row-acl grant-role',
  'row-acl grant-dept',
  'row-acl revoke-role',
  'report list',
  'report info',
  'report create',
  'report update',
  'report copy',
  'report publish',
  'report delete',
  'report archive',
  'report validate',
  'report sort',
  'report move',
  'report preview',
  'report query',
  'report query-widget',
  'report widget-add',
  'report widget-update',
  'report widget-delete',
  'report widget-batch',
  'report widget-sort',
  'ai chat-completions',
  'canvas create',
  'canvas info',
  'canvas save',
  'canvas versions',
  'canvas version',
  'canvas restore',
  'canvas resource-list',
  'canvas resource-save',
  'canvas resource-delete',
  'canvas resource-publish',
  'canvas resource-market',
];

export const SKILL_MAPPINGS: Record<string, SkillMapping> = {
  'dimens-system-orchestrator': {
    version: '1.0.0',
    tags: ['system', 'orchestrator', 'planner', 'routing', 'builder'],
    commandGroups: ['skill'],
    commands: ['skill list', 'skill recommend', 'skill info', 'skill show'],
    sdkModules: [],
    toolNames: ['system_decomposition', 'skill_routing'],
  },
  'dimens-manager': {
    version: '1.0.0',
    tags: [
      'manager',
      'auth',
      'project',
      'sheet',
      'table',
      'document',
      'permission',
      'workflow',
      'report',
      'canvas',
    ],
    commandGroups: MANAGER_COMMAND_GROUPS,
    commands: MANAGER_COMMANDS,
    sdkModules: [
      'AuthSDK',
      'ProjectSDK',
      'SheetSDK',
      'ColumnSDK',
      'ViewSDK',
      'RowSDK',
      'DocumentSDK',
      'UploadSDK',
      'RoleSDK',
      'PermissionSDK',
      'RowPolicySDK',
      'RowAclSDK',
      'ReportSDK',
      'CanvasSDK',
      'FlowChatSDK',
      'DimensSDK.auth',
      'DimensSDK.project',
      'DimensSDK.sheet',
      'DimensSDK.column',
      'DimensSDK.view',
      'DimensSDK.row',
      'DimensSDK.document',
      'DimensSDK.upload',
      'DimensSDK.role',
      'DimensSDK.permission',
      'DimensSDK.rowPolicy',
      'DimensSDK.rowAcl',
      'DimensSDK.report',
      'DimensSDK.canvas',
      'DimensSDK.ai',
    ],
    toolNames: [
      'api_key_create',
      'team_info',
      'project_list',
      'project_create',
      'sheet_create',
      'column_create',
      'view_create',
      'row_update',
      'document_update',
      'file_upload',
      'permission_resolve',
      'row_policy_check',
      'report_create',
      'report_query',
      'canvas_create',
      'canvas_save',
      'canvas_resource_publish',
      'flow_run_invoke',
    ],
  },
  'dimens-sdk': {
    version: '1.0.0',
    tags: ['sdk', 'http', 'web', 'mobile', 'bff', 'integration'],
    commandGroups: ['auth', 'upload', 'ai', 'project', 'sheet', 'doc', 'report'],
    commands: [
      'auth api-key-login',
      'auth refresh',
      'upload file',
      'ai chat-completions',
      'project list',
      'project info',
      'sheet list',
      'sheet info',
      'doc info',
      'doc update',
      'report info',
      'report query',
      'report query-widget',
    ],
    sdkModules: [
      'createSDK',
      'DimensSDK',
      'AuthSDK',
      'UploadSDK',
      'ProjectSDK',
      'SheetSDK',
      'DocumentSDK',
      'ReportSDK',
      'FlowChatSDK',
    ],
    toolNames: ['sdk_integration', 'http_api', 'frontend_auth_flow', 'bff_proxy'],
  },
};

export function getSkillMapping(name: string): SkillMapping | undefined {
  return SKILL_MAPPINGS[name];
}
