import type { Skill } from '../types';

type SkillMapping = Pick<
  Skill,
  'commandGroups' | 'commands' | 'sdkModules' | 'toolNames' | 'tags' | 'version'
>;

const MANAGER_COMMAND_GROUPS = [
  'auth',
  'user',
  'team',
  'project',
  'sheet',
  'column',
  'view',
  'row',
  'doc',
  'json-field',
  'richtext-field',
  'upload',
  'role',
  'permission',
  'row-policy',
  'row-acl',
  'report',
  'ai',
  'canvas',
  'workflow-public',
  'plugin-public',
];

const MANAGER_COMMANDS = [
  'auth login',
  'auth api-key-login',
  'auth refresh',
  'auth me',
  'auth status',
  'auth use-team',
  'auth use-project',
  'auth profile',
  'user me',
  'team info',
  'team users',
  'project list',
  'project info',
  'project create',
  'project update',
  'project trash',
  'project restore',
  'project use',
  'sheet list',
  'sheet tree',
  'sheet create',
  'sheet info',
  'sheet update',
  'sheet delete',
  'sheet structure',
  'column list',
  'column create',
  'column update',
  'column delete',
  'view list',
  'view create',
  'row page',
  'row info',
  'row open-info',
  'row create',
  'row batch-create',
  'row update',
  'row delete',
  'row set-cell',
  'doc create',
  'doc info',
  'doc update',
  'doc delete',
  'doc versions',
  'doc version',
  'doc restore',
  'doc attach-file',
  'doc append-image',
  'json-field content',
  'json-field save',
  'richtext-field content',
  'richtext-field save',
  'upload file',
  'upload mode',
  'role list',
  'role info',
  'role create',
  'role update',
  'role delete',
  'role assign-user',
  'role revoke-user',
  'permission list',
  'permission create',
  'permission update',
  'permission delete',
  'permission set-resource',
  'row-policy list',
  'row-policy create',
  'row-policy update',
  'row-policy delete',
  'row-policy enable',
  'row-policy disable',
  'row-acl list',
  'row-acl grant-user',
  'row-acl grant-role',
  'row-acl grant-dept',
  'row-acl revoke-role',
  'report list',
  'report info',
  'report create',
  'report update',
  'report copy',
  'report publish',
  'report delete',
  'report archive',
  'report validate',
  'report sort',
  'report move',
  'report preview',
  'report query',
  'report query-widget',
  'report widget-add',
  'report widget-update',
  'report widget-delete',
  'report widget-batch',
  'report widget-sort',
  'ai chat-completions',
  'workflow-public get',
  'workflow-public upsert',
  'workflow-public disable',
  'workflow-public reset-secret',
  'workflow-public invoke',
  'plugin-public publish',
  'plugin-public list',
  'plugin-public detail',
  'plugin-public install',
  'plugin-public install-flow',
  'plugin-public uninstall',
  'plugin-public upgrade',
  'canvas create',
  'canvas info',
  'canvas save',
  'canvas versions',
  'canvas version',
  'canvas restore',
  'canvas resource-list',
  'canvas resource-save',
  'canvas resource-delete',
  'canvas resource-publish',
  'canvas resource-market',
];

export const SKILL_MAPPINGS: Record<string, SkillMapping> = {
  'dimens-system-orchestrator': {
    version: '1.0.2',
    tags: ['system', 'orchestrator', 'planner', 'routing', 'builder'],
    commandGroups: ['skill', 'system'],
    commands: ['skill list', 'skill recommend', 'skill info', 'skill show', 'system create', 'create'],
    sdkModules: [],
    toolNames: ['system_decomposition', 'skill_routing'],
  },
  'dimens-manager': {
    version: '1.0.2',
    tags: [
      'manager',
      'auth',
      'user',
      'team',
      'project',
      'sheet',
      'table',
      'document',
      'permission',
      'workflow',
      'public-workflow',
      'market',
      'plugin',
      'report',
      'canvas',
      'json-field',
      'richtext-field',
    ],
    commandGroups: MANAGER_COMMAND_GROUPS,
    commands: MANAGER_COMMANDS,
    sdkModules: [
      'AuthSDK',
      'UserSDK',
      'TeamSDK',
      'ProjectSDK',
      'SheetSDK',
      'ColumnSDK',
      'ViewSDK',
      'RowSDK',
      'DocumentSDK',
      'UploadSDK',
      'RoleSDK',
      'PermissionSDK',
      'RowPolicySDK',
      'RowAclSDK',
      'ReportSDK',
      'CanvasSDK',
      'FlowChatSDK',
      'JsonFieldSDK',
      'WorkflowPublicSDK',
      'PluginPublicSDK',
      'DimensSDK.auth',
      'DimensSDK.user',
      'DimensSDK.team',
      'DimensSDK.project',
      'DimensSDK.sheet',
      'DimensSDK.column',
      'DimensSDK.view',
      'DimensSDK.row',
      'DimensSDK.document',
      'DimensSDK.jsonField',
      'DimensSDK.richtextField',
      'DimensSDK.upload',
      'DimensSDK.role',
      'DimensSDK.permission',
      'DimensSDK.rowPolicy',
      'DimensSDK.rowAcl',
      'DimensSDK.report',
      'DimensSDK.canvas',
      'DimensSDK.ai',
      'DimensSDK.workflowPublic',
      'DimensSDK.pluginPublic',
    ],
    toolNames: [
      'api_key_create',
      'team_info',
      'project_list',
      'project_create',
      'sheet_create',
      'column_create',
      'view_create',
      'row_info',
      'open_row_info',
      'row_update',
      'document_update',
      'file_upload',
      'permission_resolve',
      'row_policy_check',
      'report_create',
      'report_query',
      'canvas_create',
      'canvas_save',
      'canvas_resource_publish',
      'flow_run_invoke',
      'workflow_public_access_get',
      'workflow_public_access_upsert',
      'workflow_public_chat_completions',
      'flow_plugin_publish_public',
      'flow_plugin_market_install',
      'richtext_field_save',
    ],
  },
  'dimens-sdk': {
    version: '1.0.2',
    tags: ['sdk', 'http', 'web', 'mobile', 'bff', 'node', 'integration'],
    commandGroups: [
      'auth',
      'user',
      'team',
      'upload',
      'ai',
      'project',
      'system',
      'sheet',
      'column',
      'view',
      'row',
      'doc',
      'json-field',
      'richtext-field',
      'report',
      'canvas',
      'workflow-public',
      'plugin-public',
    ],
    commands: [
      'auth api-key-login',
      'auth refresh',
      'auth me',
      'auth status',
      'user me',
      'team info',
      'team users',
      'upload file',
      'upload mode',
      'ai chat-completions',
      'project list',
      'project info',
      'system create',
      'create',
      'sheet list',
      'sheet info',
      'sheet structure',
      'column list',
      'view list',
      'row page',
      'row info',
      'row open-info',
      'doc info',
      'doc update',
      'json-field content',
      'json-field save',
      'richtext-field content',
      'richtext-field save',
      'report info',
      'report preview',
      'report query',
      'report query-widget',
      'canvas info',
      'canvas save',
      'canvas versions',
      'canvas resource-save',
      'canvas resource-publish',
      'workflow-public invoke',
      'workflow-public get',
      'workflow-public upsert',
      'workflow-public reset-secret',
      'plugin-public list',
      'plugin-public detail',
      'plugin-public install-flow',
    ],
    sdkModules: [
      'createSDK',
      'DimensSDK',
      'AuthSDK',
      'UserSDK',
      'TeamSDK',
      'CanvasSDK',
      'ColumnSDK',
      'DocumentSDK',
      'DimensClient',
      'FlowChatSDK',
      'JsonFieldSDK',
      'WorkflowPublicSDK',
      'PluginPublicSDK',
      'PermissionSDK',
      'ProjectSDK',
      'ReportSDK',
      'RichTextFieldSDK',
      'RoleSDK',
      'RowAclSDK',
      'RowPolicySDK',
      'RowSDK',
      'SheetSDK',
      'UploadSDK',
      'ViewSDK',
      'DimensSDK.jsonField',
      'DimensSDK.workflowPublic',
      'DimensSDK.pluginPublic',
    ],
    toolNames: [
      'sdk_integration',
      'http_api',
      'frontend_auth_flow',
      'bff_proxy',
      'node_sdk',
      'mobile_bridge',
      'resource_api',
      'public_workflow_api',
      'public_plugin_market_api',
      'row_info',
      'open_row_info',
      'file_upload',
    ],
  },
};

export function getSkillMapping(name: string): SkillMapping | undefined {
  return SKILL_MAPPINGS[name];
}
